feature/rubocop capybara fixess (#542)
* click button deprecated

* click link  deprecated

* update to keep ruby version updated

* chore: Update Ruby version in GitHub Actions workflow

* adds mac os package frum to speed up ruby version management
adds script to get the latest ruby

* mend

* ignore the database files

* cleanup database files

* prevent sqlite3 from breaking rails on version 2

* fix for github action build  Unknown version 3.3.3p89

* fix for extracting major.minor ruby version to use in github ruby build

* fix for Gemfile Reading RUBY_VERSION with only major and minor

* fix for Gemfile Reading RUBY_VERSION with only major and minor

* fix for Gemfile Reading RUBY_VERSION with only major and minor

* bugfix for major_minor_ruby_version

* bugfix for major_minor_version

* remove ruby-version files

* fix another typoo

* fix for next? not being true in Gemfile

* fix for Installing websocket-driver 0.7.6 with native extensions
Using net-protocol 0.2.2
Downloading net-pop-0.1.2 revealed dependencies not in the API or the lockfile
(net-protocol (>= 0)).
Running `bundle update net-pop` should fix the problem.
Error: The process /opt/hostedtoolcache/Ruby/3.3.3/x64/bin/bundle failed with exit code 34"

* fix the missing dependency

* fix the missing dependency

* dependencies for two arch

* Fix pipeline issue where the ruby github action tries to manage the Gemfile.next.lock

* try to fix missing dependency in Gemfile.next.lock on ubuntu

* another attempt

* dependabot maybe fixed

* dependabot maybe fixed from updating sqlite3

* keep consistant on the source of the ruby install

* return to a working Gemfile.lock

---------

Signed-off-by: jcowhigjr <jcowhigjr+dev@gmail.com>